---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-claim1
  namespace: kafka
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
