apiVersion: v1
kind: Service
metadata:
  name: external-service-3
  namespace: kafka
spec:
  type: NodePort
  selector:
    statefulset.kubernetes.io/pod-name: kafka-3
  ports:
  - protocol: TCP
    port: 32403
    nodePort: 32403
    targetPort: 9094
