apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURDekNDQWZPZ0F3SUJBZ0lRUHlQYWRlSVIwVkFGdlk2a21XTERtVEFOQmdrcWhraUc5dzBCQVFzRkFEQXYKTVMwd0t3WURWUVFERXlRM056RmxOR0UwT0Mxak0yWmlMVFF5WlRFdFlqZGtaUzFtWlRoaVlUY3pZV1l5TmpJdwpIaGNOTWpBd016TXdNVEkxTlRNeFdoY05NalV3TXpJNU1UTTFOVE14V2pBdk1TMHdLd1lEVlFRREV5UTNOekZsCk5HRTBPQzFqTTJaaUxUUXlaVEV0WWpka1pTMW1aVGhpWVRjellXWXlOakl3Z2dFaU1BMEdDU3FHU0liM0RRRUIKQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUN5Y0cwNVpXblBZanVBUkdjVHBLRmpKQXljNUFVdjhwTmJveWFzOEpRagppbmhDK0d0MWFsMHc5bTRtTE44WndOTXVKYWg4T0hzdnJqTGhHRUcrUlM4dGpnRUJSTjRjSFBlSGNXQi95UGdrCnk3MFk0SndQZjJpR3lMN1I0MzhXMklFY29XWFZ4T0lFajZmaHVhM0ZBK3c1a2lKMUZ1RGFtL2RKVDh2NzVHM0IKY3VFU2t3TTNNcEJhZUNPNWNLTG1oZUdQcFA1UUxqMThFYWI5TmVPSy9QN1N4SzFTM0U1UEE0Z1U4WjYyTjZUKwpSOE9CZ1VxZ3hWcGVpUVNjd2tZV2xJSmQvSkNsS2NMaGF4aHhXMkFuM1BnQjVQNVhVcTZhdnp6WTNUcytrcWFNCnNqeWN1K1dDSFZEeS9VVXFtWDJnQ0VpN0Q4anNNWU1OWmV1NFNpT01RNWgzQWdNQkFBR2pJekFoTUE0R0ExVWQKRHdFQi93UUVBd0lDQkRBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFCQQpQUG1seGVPV0t1aE93M21nZDdlaEtJTy9MU3ZnNmN6VXcxWHpiVEplY2pzdTBLQjNkMER4UDdVNVdLSmVPQUlmCkJGVUZWV0QwQjFucGNhT21Oc2s1ZHdXLzkyTEl5bm80YjV1UkFYb0lLc1VqRFIzYWIvMjMzQ2FDSVh5VnZNd0gKVnJab0J4ckVSZWgydXBvZTl1LzBsVkVaREpVQ2pnakZBbUE0R0RwckgwZ3VDQWEvN0Q2ZTRJUlZGYWdLdWdXKwpBSmkwMDU3eUtSQk9PZ0hjV2NLTjdoOXV4ZjNCcVhGV21GQmkwbFFWVjdDZmNZOENYZ0hORE9WcVZWS1YyLysvCkl6MStpaEJZTHFoejJDTTR2aTJYZHFOaWw1Q2tVSXFOUndoTkJFamN3MFV0M3pwcWo1UUVmeG9pNGRxNzJRa3IKMERzNVppSFNwWU5yK2N3aUFBVkwKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://35.234.132.79
  name: cluster-1
contexts:
- context:
    cluster: cluster-1
    user: user-1
  name: my-cluster
current-context: my-cluster
kind: Config
preferences: {}
users:
- name: user-1
  user:
    auth-provider:
      config:
        access-token: ya29.c.KpABxAc-dA7bPO-bw9an2a-TJqVYhjY1bBAnz_ubtaXfZDYb6JUU6edsFNiD-D60wrSq_JgSD03rfEzj91hRLb_1up3-g_YGwKKygUaeauaEu1ppWazF-WrnpqAwy7K4b6VitDXv1-843IcdzyuCOp2wV455f7JYoDxQbd8w27Flz6jWai36v7PGjkFDll5qekRV
        expiry: "2020-03-31T15:00:25.118582529Z"
      name: gcp
