apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: dns-proxy
  name: dns-proxy
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: dns-proxy
    spec:
      containers:
      - env:
        - name: MG_LOG_LEVEL
          value: ERROR
        image: defreitas/dns-proxy-server
        name: dns-proxy
        resources: {}
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: dns-proxy-claim0
        - mountPath: /etc/resolv.conf
          name: dns-proxy-claim1
      hostname: dns-proxy
      restartPolicy: Always
      volumes:
      - name: dns-proxy-claim0
        persistentVolumeClaim:
          claimName: dns-proxy-claim0
      - name: dns-proxy-claim1
        persistentVolumeClaim:
          claimName: dns-proxy-claim1
status: {}
