# NOte - uses custom hostnames, but a single IP address...
version: '3.2'

services:
  dns-proxy:
    image: defreitas/dns-proxy-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/resolv.conf:/etc/resolv.conf
    environment:
      - MG_LOG_LEVEL=ERROR
    hostname: dns-proxy
    networks:
      dns-proxy:
        ipv4_address: 172.0.0.10

  zoo1:
    image: zookeeper:3.4.14
    container_name: zookeeper
    hostname: zoo1
    ports:
      - "2181:2181"
    environment:
        ZOO_MY_ID: 1
        ZOO_PORT: 2181
        ZOO_SERVERS: server.1=zoo1:2888:3888
    volumes:
      - ./data/zoo1/data:/data
      - ./data/zoo1/datalog:/datalog
    dns:
      - 172.0.0.10
    networks:
      - dns-proxy
 
  kafka0:
    image: wurstmeister/kafka
    container_name: kafka0
    hostname: kafka0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: -1
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_LISTENERS: PLAINTEXT://kafka0:9092
    volumes:
      - ./data/kafka0/data:/var/lib/kafka/data
    depends_on:
      - zoo1
    dns:
      - 172.0.0.10
    networks:
      - dns-proxy

  kafka1:
    image: wurstmeister/kafka
    container_name: kafka1
    hostname: kafka1
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: -1
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_LISTENERS: PLAINTEXT://kafka1:9093
    volumes:
      - ./data/kafka1/data:/var/lib/kafka/data
    depends_on:
      - zoo1
    dns:
      - 172.0.0.10
    networks:
      - dns-proxy

  kafka2:
    image: wurstmeister/kafka
    container_name: kafka2
    hostname: kafka2
    ports:
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: -1
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_LISTENERS: PLAINTEXT://kafka2:9094
    volumes:
      - ./data/kafka2/data:/var/lib/kafka/data
    depends_on:
      - zoo1
    dns:
      - 172.0.0.10
    networks:
      - dns-proxy

networks:
  dns-proxy:
    ipam:
      config:
        - subnet: 172.0.0.0/24
