apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: kafka1
  name: kafka1
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: kafka1
    spec:
      containers:
      - env:
        - name: KAFKA_BROKER_ID
          value: "-1"
        - name: KAFKA_LISTENERS
          value: PLAINTEXT://kafka1:9093
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo1:2181
        image: wurstmeister/kafka
        name: kafka1
        ports:
        - containerPort: 9093
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/kafka/data
          name: kafka1-claim0
      hostname: kafka1
      restartPolicy: Always
      volumes:
      - name: kafka1-claim0
        persistentVolumeClaim:
          claimName: kafka1-claim0
status: {}
