apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: kafka2
  name: kafka2
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: kafka2
    spec:
      containers:
      - env:
        - name: KAFKA_BROKER_ID
          value: "-1"
        - name: KAFKA_LISTENERS
          value: PLAINTEXT://kafka2:9094
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo1:2181
        image: wurstmeister/kafka
        name: kafka2
        ports:
        - containerPort: 9094
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/kafka/data
          name: kafka2-claim0
      hostname: kafka2
      restartPolicy: Always
      volumes:
      - name: kafka2-claim0
        persistentVolumeClaim:
          claimName: kafka2-claim0
status: {}
