---
apiVersion: v1
kind: Service
metadata:
  name: zoo0
  namespace: kafka
  labels:
    run: zoo0
spec:
  ports:
    - port: 2181
      targetPort: 2181
  selector:
    run: zoo0
  type: ClusterIP
status: {}
