---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zoo0
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      run: zoo0
  template:
    metadata:
      labels:
        run: zoo0
    spec:
      hostname: zoo1
      containers:
        - name: zookeeper
          image: zookeeper:3.6.0
          ports:
            - containerPort: 2181
          env:
            - name: ZOO_MY_ID
              value: "0"
            - name: ZOO_PORT
              value: "2181"
            - name: ZOO_SERVERS
              value: server.1=zoo0:2888:3888
          resources: {}
          volumeMounts:
            - mountPath: /data
              name: zoo0-claim0
            - mountPath: /datalog
              name: zoo0-claim1
      volumes:
        - name: zoo0-claim0
          persistentVolumeClaim:
            claimName: zoo0-claim0
        - name: zoo0-claim1
          persistentVolumeClaim:
            claimName: zoo0-claim1
      tolerations:
        - key: "is-kafka-broker-node"
          operator: "Exists"
          effect: "NoSchedule"
status: {}
