---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zoo1
spec:
  replicas: 1
  selector:
    matchLabels:
      name: zookeeper-1
  template:
    metadata:
      labels:
        name: zookeeper-1
    spec:
      hostname: zoo1
      containers:
        - name: zookeeper
          image: zookeeper:3.4.14
          ports:
            - containerPort: 2181
          env:
            - name: ZOO_MY_ID
              value: "1"
            - name: ZOO_PORT
              value: "2181"
            - name: ZOO_SERVERS
              value: server.1=zoo1:2888:3888
          resources: {}
          volumeMounts:
            - mountPath: /data
              name: zoo1-claim0
            - mountPath: /datalog
              name: zoo1-claim1
      volumes:
        - name: zoo1-claim0
          persistentVolumeClaim:
            claimName: zoo1-claim0
        - name: zoo1-claim1
          persistentVolumeClaim:
            claimName: zoo1-claim1
status: {}
