apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: kafka
spec:
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5556"
    spec:
      containers:
      - name: kafka-prometheus-sidecar 
        image: nichemley/fs-kafka-prometheus-image
        ports:
        - containerPort: 5556 
          # prometheus.op/port is no longer "honored"
          name: metrics
        resources:
          requests:
            cpu: 0m
            memory: 60Mi

