apiVersion: v1
kind: Service
metadata:
  name: external-service-2
  namespace: kafka
spec:
  type: NodePort 
  selector:
    statefulset.kubernetes.io/pod-name: kafka-2
  ports:
  - protocol: TCP
    port: 32402 
    nodePort: 32402 
    targetPort: 9094
