apiVersion: v1
kind: Service
metadata:
  name: external-service-1
  namespace: kafka
spec:
  type: NodePort 
  selector:
    statefulset.kubernetes.io/pod-name: kafka-1
  ports:
  - protocol: TCP
    nodePort: 32401 
    port: 32401
    targetPort: 9094
