apiVersion: v1
kind: Service
metadata:
  name: external-service-4
  namespace: kafka
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    statefulset.kubernetes.io/pod-name: kafka-4
  ports:
  - protocol: TCP
    port: 32404
    nodePort: 32404
    targetPort: 9094
