apiVersion: v1
kind: Service
metadata:
  name: external-service-5
  namespace: kafka
spec:
  type: NodePort
  selector:
    statefulset.kubernetes.io/pod-name: kafka-5
  ports:
  - protocol: TCP
    port: 32405
    nodePort: 32405
    targetPort: 9094
