apiVersion: v1
kind: Service
metadata:
  name: external-service-6
  namespace: kafka
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    statefulset.kubernetes.io/pod-name: kafka-6
  ports:
  - protocol: TCP
    port: 32406
    nodePort: 32406
    targetPort: 9094
