apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURDekNDQWZPZ0F3SUJBZ0lRSGxIQVc4MTZ4Yk84Q3lwN2VjUUtNVEFOQmdrcWhraUc5dzBCQVFzRkFEQXYKTVMwd0t3WURWUVFERXlRMVpETTNaREE0TWkwMFlUZGpMVFJrTkRFdE9UZzFZeTAzTVdNME5EY3pOVFkyWmpRdwpIaGNOTWpBd01URTBNRGt4TkRVeldoY05NalV3TVRFeU1UQXhORFV6V2pBdk1TMHdLd1lEVlFRREV5UTFaRE0zClpEQTRNaTAwWVRkakxUUmtOREV0T1RnMVl5MDNNV00wTkRjek5UWTJaalF3Z2dFaU1BMEdDU3FHU0liM0RRRUIKQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUURtcUpySGh5aW5CM1gvSWxOSnpvcGdZakN6OEI5UWNkUEM4Rk1weHJzWApaaDhTY2R1S0dodStETlZvN21lRGhHRFYwWTJ6d1hVc1JVbCtPb0xjWGZ5SjhmQ2x6SmU5NDRHZnorZjZwRkxBCkhUdVNDWXBkS0tTd0s4UkRMK1ZiK0R4dXEyWE82cHB0ZDhUeWhrYXdaQk05dnlLbjEreDRnc24zMy9OVGQ1VnYKY05EaTRvMTdhSlJxUktsdXlmMzhFWjRnSFFhOW94UlJwTHdqMmprdVg1Q29adXFoMFIzL3BTVm1BV1owaVprWQpTZ1RrU01ybEl4SGQ3UEx1OG9HR2laU1FnUDROWjVYYk1FT1pEaTVnTHBkL3VrR3Fjc2NDdEFZVHhSMU5mMkJBCjFJT1JnQlE0T0RtaElsRmNoMkRtc1RXQ3BLY08xQzlqY2IvUlNvNExqcWc3QWdNQkFBR2pJekFoTUE0R0ExVWQKRHdFQi93UUVBd0lDQkRBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFBaAptRG5La08za2JoYTQzQXFLQndYSzU5SnlWa0VQc0VyVkZ6ZzVSNE9ZSmh0MlhJaXJMVERFaDdOalFEbEk1M0FSClc0OHIvZVpXS254RURxOEJtVnFXWDZxaldFUExOVTdnRDNTN241QTVnSXdqdWw1QndzYXFIVzVkQnExWlBNaEgKYkExVVpLRDVxbmRNZTcrY3BYQmg4c0hnYnVTcUFGMytkRWl0RXd1akNTQzZXcFV1bElLQjhySEJETDVmVUUyNwptRnBPaVIwc0xDREttTWdmaWdadlRtK0pMelpBNlJGUE5mQm9HV3N0TnBtd3dqUk5kRGtxaFB0WW9OTFZaWkpqClg1cWVhTjl0RldnaVlTQkpoMEU4YXdsSUNKVDZDUkhtd0Q1U2I5aEtCbVRPQ0ZmZ0ZSMTZmeCt2N1V4aHFxUjcKTmlycXYvN3lGME84Y1hzS2cxMlcKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://35.234.145.95
  name: cluster-1
contexts:
- context:
    cluster: cluster-1
    user: user-1
  name: my-cluster
current-context: my-cluster
kind: Config
preferences: {}
users:
- name: user-1
  user:
    auth-provider:
      config:
        access-token: ya29.c.Kl-5B7b0DaPYPhZJpKYokS6fMGqMiVzbrPpTM0H_pR28QbbWbGVaveTevvswAdTNnZgcZJIpwoBxKk8_n-P-jKgN3IcuaYJXsgxK657gRQRLxF7Bmqnh2XbLWN0cqhbPEQ
        expiry: "2020-01-14T14:01:12.986978453Z"
      name: gcp
