apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURDekNDQWZPZ0F3SUJBZ0lRUFFYL0VzYzNET1ZYamlScXJXR1k5REFOQmdrcWhraUc5dzBCQVFzRkFEQXYKTVMwd0t3WURWUVFERXlRMU16VTJaamN4WXkxaFpEQXpMVFJrTmpjdFltSTJaaTAxWm1Vd1lUWmxZVGRpWTJJdwpIaGNOTWpBd01qSTBNVEUxTVRJNFdoY05NalV3TWpJeU1USTFNVEk0V2pBdk1TMHdLd1lEVlFRREV5UTFNelUyClpqY3hZeTFoWkRBekxUUmtOamN0WW1JMlppMDFabVV3WVRabFlUZGlZMkl3Z2dFaU1BMEdDU3FHU0liM0RRRUIKQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUURFUmZjT255N3NWSmU0VTJDWEpTUWpJaEtCdERNRTdyaUhiQ1NlWWI3dwp1aUd3M2wyb0MzODFrVjZVZm9MVmFCNUFKOG9yZXZLbWdQbVZyMEk2QVFwRDFNZ2hyYURSVXhzQ2F5alJ5VlBoCk5aZFpoOWFOU0xUNFV1VkxUMkd6SGZ6RE9CUGpJOXFraXdOcDlVMUd2bCtyUjBtNHUrdENucG9MREVTQThPNHYKdkZXejlVOTc3MlBBdkFjR2RJMVRWZWN3N05HSWlmWHNxUkUySzkyVVNaODJpV0tlUk9MeWR2RWk0NVltWDFpbgptQ1poVWRtZmpHN2diTUw1bTM3QlNBRlVUVG5JSlFrOU1XVmprNjdxbCtrZXZlbkhiWnNqQlFOYUsrZ2syU0tHCnF2aFhxenJYeU5ZQTlWNXEwd01NV0Yxa0drOGlwbUtOcWYxTFJKZGltUUFCQWdNQkFBR2pJekFoTUE0R0ExVWQKRHdFQi93UUVBd0lDQkRBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFCOQpLdTZkZFhRVXdLODZ6N3BNUk1xK0dxcmpkb2YwTnRWc0grNmJhRndEaWtUdHA2R1RxNmtsL2pTSlNmSndBb0g3Cm5jVzVoU2FMOW1OOGNpU2hhT2ZLU3hiSE5sZFMyM3puVklobnUxOTR4N1k2OHRDU1FNU0tBMjd2T2lsYVBiODMKa0QydUp4SDJueUhQTno5U29EMkxMTzhiU2gvWHRqUFh0dnU1dU16U2VmK1dvNFVLSWsvbWFVd2J1TDFaZnQxaApPTXpHY0FDZXp1VEIvdktDVnF5cVhDK2tNN1dVWGtBdGxCdjlnV2s4NjNONW56bUlheENtS2pNRzVTRzJIamtuCklaSE5aUHlEZm1sa3hBNE9VZ1NpVDdMemxSMmNzWS9XRUNFTzlIVjRtMHl6VjBKM2NwT2h6MXZ1NStMbzh2Z1kKblF2Y3BLcENhUVpDeTI1V1o4T1oKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://35.197.209.244
  name: cluster-1
contexts:
- context:
    cluster: cluster-1
    user: user-1
  name: my-cluster
current-context: my-cluster
kind: Config
preferences: {}
users:
- name: user-1
  user:
    auth-provider:
      config:
        access-token: ya29.c.KpABvwdbqxZkfKYiUOxwfplAdaLVXfG0sYQ7r8liDDfCnCtTpYcwbwR4WG99echQLz_GwST_G620JmiAC1mGTjb_aoLlCfGrT-Tpo_aZQsXjYA7QPdPwrwlgofp1pEfYPKUy27FpwDP0_KpQseU9j_lyASZief-w8SJwozu5nxhyyUrbA-MrZTu49MbHn4YfXtTZ
        expiry: "2020-02-24T14:16:31.506102815Z"
      name: gcp
