apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURDekNDQWZPZ0F3SUJBZ0lRSGxIQVc4MTZ4Yk84Q3lwN2VjUUtNVEFOQmdrcWhraUc5dzBCQVFzRkFEQXYKTVMwd0t3WURWUVFERXlRMVpETTNaREE0TWkwMFlUZGpMVFJrTkRFdE9UZzFZeTAzTVdNME5EY3pOVFkyWmpRdwpIaGNOTWpBd01URTBNRGt4TkRVeldoY05NalV3TVRFeU1UQXhORFV6V2pBdk1TMHdLd1lEVlFRREV5UTFaRE0zClpEQTRNaTAwWVRkakxUUmtOREV0T1RnMVl5MDNNV00wTkRjek5UWTJaalF3Z2dFaU1BMEdDU3FHU0liM0RRRUIKQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUURtcUpySGh5aW5CM1gvSWxOSnpvcGdZakN6OEI5UWNkUEM4Rk1weHJzWApaaDhTY2R1S0dodStETlZvN21lRGhHRFYwWTJ6d1hVc1JVbCtPb0xjWGZ5SjhmQ2x6SmU5NDRHZnorZjZwRkxBCkhUdVNDWXBkS0tTd0s4UkRMK1ZiK0R4dXEyWE82cHB0ZDhUeWhrYXdaQk05dnlLbjEreDRnc24zMy9OVGQ1VnYKY05EaTRvMTdhSlJxUktsdXlmMzhFWjRnSFFhOW94UlJwTHdqMmprdVg1Q29adXFoMFIzL3BTVm1BV1owaVprWQpTZ1RrU01ybEl4SGQ3UEx1OG9HR2laU1FnUDROWjVYYk1FT1pEaTVnTHBkL3VrR3Fjc2NDdEFZVHhSMU5mMkJBCjFJT1JnQlE0T0RtaElsRmNoMkRtc1RXQ3BLY08xQzlqY2IvUlNvNExqcWc3QWdNQkFBR2pJekFoTUE0R0ExVWQKRHdFQi93UUVBd0lDQkRBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFBaAptRG5La08za2JoYTQzQXFLQndYSzU5SnlWa0VQc0VyVkZ6ZzVSNE9ZSmh0MlhJaXJMVERFaDdOalFEbEk1M0FSClc0OHIvZVpXS254RURxOEJtVnFXWDZxaldFUExOVTdnRDNTN241QTVnSXdqdWw1QndzYXFIVzVkQnExWlBNaEgKYkExVVpLRDVxbmRNZTcrY3BYQmg4c0hnYnVTcUFGMytkRWl0RXd1akNTQzZXcFV1bElLQjhySEJETDVmVUUyNwptRnBPaVIwc0xDREttTWdmaWdadlRtK0pMelpBNlJGUE5mQm9HV3N0TnBtd3dqUk5kRGtxaFB0WW9OTFZaWkpqClg1cWVhTjl0RldnaVlTQkpoMEU4YXdsSUNKVDZDUkhtd0Q1U2I5aEtCbVRPQ0ZmZ0ZSMTZmeCt2N1V4aHFxUjcKTmlycXYvN3lGME84Y1hzS2cxMlcKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://35.234.145.95
  name: cluster-1
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURERENDQWZTZ0F3SUJBZ0lSQUlhcHZ2UXIrV0ZYaUxXSWc0UnhGOEl3RFFZSktvWklodmNOQVFFTEJRQXcKTHpFdE1Dc0dBMVVFQXhNa1kyRXlZalkxTTJVdE0ySmxOQzAwTW1RNExXRmhZbVl0TjJWa05XSTFOek0zTXpFMwpNQjRYRFRJd01ERXlNVEE0TkRReU5Gb1hEVEkxTURFeE9UQTVORFF5TkZvd0x6RXRNQ3NHQTFVRUF4TWtZMkV5CllqWTFNMlV0TTJKbE5DMDBNbVE0TFdGaFltWXROMlZrTldJMU56TTNNekUzTUlJQklqQU5CZ2txaGtpRzl3MEIKQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBc0FSeWFpS2pPL3lzNjNINEt6dTcxRnlodU9tdUFMcGpvbmM0LzRtNgowVGN3N3dqZ2s0Yzc2cTFad0V1a2toNThnZHR2WnhkcWVDS1A0dDdVc1g1RG9mam9qSG5taDFwZjQwNVdXWDdpCk5aL2VRUXZ6KzNXQmtTVWp5bXZNbm1Kb3RCbUZBTHh6eWJRV25JUmt4MDlGb29rR3NYVDJFdW9qRFc0aGw5R3kKUEx2OW9sR1VEdUJqL1hEcllVRy8vaHcwcEtlOFFYeGZMU2tDc1pJa0dPVTZOQTlMWWg0TnY1LzN6emdpNGtBeAp1K01WUkZtNWdiZ1NBWXJkdmkrd0ZlT2gxUjZUTXRISFJ0c29sQVFaRHZ6eFNCTmpaYzRwUkRDR0U4aEZaWmRSCnFvTUs0QWNZWnJ1S3RSRmNPMmVLTXNOelp1Y29icXJicVk3bmVSK0h5dTZEWndJREFRQUJveU13SVRBT0JnTlYKSFE4QkFmOEVCQU1DQWdRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQQpic2pnMjlRbnhuNDduZUZzNlYreWVjNWZ4eEpXWXUxLzA0c2p4dWlFM0o2SmVoS045TUtyblNsNkhHMzQ5dk5CCnNpOHNJSkZCUWlHNVV5K3I0NUhiUk05Y1hIalpLUmJlb0R1eTAyYXh4VlhsRjNSOGtlTVh6V1ZJOTd1M1JyOFgKdXRwSnZMaVpQem9NRWE3UE5QWnZtb1BuOGc0b2MxUk1RQjIrY0t4enpEdWJwR29hQ1dGRkphdW5jRVQ5WU9CdAp3NDhpTWpmWXJnU2RJSGxiZGtwcU55Q1FsLy9vdzB3U0NwTWxVQWpNYTFsTXlsOEU5SGxYN3ljMjMvWlppbVM4CnNrOElTUXp4Sm5zQWd0ZkNuWTZ4V296d0psN3dWcGx0dkUxWE5DeWNxczZ1VFZQVVJ5UFlGUEhCMW4xVllPWXAKeEF3Ukk0TVpMTHZrMUlpWXlXbUNkZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://35.197.214.195
  name: gke_sturdy-shelter-259721_europe-west2_gke-kafka-cluster
contexts:
- context:
    cluster: gke_sturdy-shelter-259721_europe-west2_gke-kafka-cluster
    user: gke_sturdy-shelter-259721_europe-west2_gke-kafka-cluster
  name: gke_sturdy-shelter-259721_europe-west2_gke-kafka-cluster
- context:
    cluster: cluster-1
    user: user-1
  name: my-cluster
current-context: gke_sturdy-shelter-259721_europe-west2_gke-kafka-cluster
kind: Config
preferences: {}
users:
- name: gke_sturdy-shelter-259721_europe-west2_gke-kafka-cluster
  user:
    auth-provider:
      config:
        access-token: ya29.Ima6B6uOAUSCpwFL4ZQDVln9xIwch3Uq622KmUOX1GVEvTMuh1nzyexLnP5NwAhhvoeZKFSHfqixI4NGt5KLc-hp7I8X8-yP_8_J9mmq28LsnU-ENh16jctJ_EafZ6ediMOEnOrQOs4
        cmd-args: config config-helper --format=json
        cmd-path: /snap/google-cloud-sdk/112/bin/gcloud
        expiry: "2020-01-21T15:01:35Z"
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
- name: user-1
  user:
    auth-provider:
      config:
        access-token: ya29.c.Kl-6B5Bx4ZA4QbsO5BOL3sHEjuRMwyr9ouidNnYhYJwrEneu8WBNAp92CtgIHQWpk7Ha2ZHIiFMh4la2X4rrDHyoR_EX60Qs4bSJnTobxMIuOdJR7AEFLDtIu9QU61Xm3Q
        expiry: "2020-01-21T10:56:12.812458557Z"
      name: gcp
