apiVersion: v1
kind: Service
metadata:
  name: internal-service-2
  namespace: kafka
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '32402'
spec:
  type: NodePort 
  selector:
    statefulset.kubernetes.io/pod-name: kafka-2
  ports:
  - protocol: TCP
    port: 32402
    nodePort: 32402
    targetPort: 9094
