apiVersion: v1
kind: Service
metadata:
  name: internal-service-1
  namespace: kafka
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '32401'
spec:
  type: NodePort 
  selector:
    statefulset.kubernetes.io/pod-name: kafka-1
  ports:
  - protocol: TCP
    port: 32401
    nodePort: 32401
    targetPort: 9094
    name: default
  - port: 32501
    nodePort: 32501
    protocol: TCP
    targetPort: 7071
    name: jmx

