apiVersion: v1
kind: Service
metadata:
  name: internal-service-5
  namespace: kafka
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '32405'
spec:
  type: NodePort 
  selector:
    statefulset.kubernetes.io/pod-name: kafka-5
  ports:
  - protocol: TCP
    port: 32405
    nodePort: 32405
    targetPort: 9094
    name: default
  - port: 32505
    nodePort: 32505
    protocol: TCP
    targetPort: 7071
    name: jmx

