apiVersion: v1
kind: Service
metadata:
  name: internal-service-6
  namespace: kafka
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '32406'
spec:
  type: NodePort 
  selector:
    statefulset.kubernetes.io/pod-name: kafka-6
  ports:
  - protocol: TCP
    port: 32406
    nodePort: 32406
    targetPort: 9094
    name: default
  - port: 32506
    nodePort: 32506
    protocol: TCP
    targetPort: 7071
    name: jmx

