apiVersion: v1
kind: Service
metadata:
  name: internal-service-4
  namespace: kafka
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '32404'
spec:
  type: NodePort 
  selector:
    statefulset.kubernetes.io/pod-name: kafka-4
  ports:
  - protocol: TCP
    port: 32404
    nodePort: 32404
    targetPort: 9094
