apiVersion: v1
kind: Service
metadata:
  name: internal-service-3
  namespace: kafka
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '32403'
spec:
  type: NodePort 
  selector:
    statefulset.kubernetes.io/pod-name: kafka-3
  ports:
  - protocol: TCP
    port: 32403
    nodePort: 32403
    targetPort: 9094
    name: default
  - port: 32503
    nodePort: 32503
    protocol: TCP
    targetPort: 7071
    name: jmx

