apiVersion: v1
kind: Service
metadata:
  name: internal-service-0
  namespace: kafka
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '32400'
spec:
  type: NodePort 
  selector:
    statefulset.kubernetes.io/pod-name: kafka-0
  ports:
  - protocol: TCP
    port: 32400
    nodePort: 32400
    targetPort: 9094
