---
kind: Deployment
apiVersion: apps/v1 
metadata:
  name: kafka0
selector:
    matchLabels:
      name: kafka0 
spec:
  template:
    metadata:
      labels:
        app: kafka
        id: "0"
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_PORT
          value: "30866"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: 192.168.99.106
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo1:2181
        - name: KAFKA_BROKER_ID
          value: "0"
        - name: KAFKA_CREATE_TOPICS
          value: test:1:1

