kind: ConfigMap
metadata:
  name: kafka-config
  namespace: kafka
apiVersion: v1
data:

  generate-config.sh: |-
    #!/bin/bash
    set -e
    set -x

    KAFKA_BROKER_ID=${HOSTNAME##*-}

    OUTSIDE_HOST=$(kubectl get node "$NODE_NAME" -o jsonpath='{.status.addresses[?(@.type=="InternalIP")].address}')

    OUTSIDE_PORT=$((32400 + ${KAFKA_BROKER_ID}))

    KAFKA_ADVERTISED_LISTENERS=OUTSIDE://${OUTSIDE_HOST}:${OUTSIDE_PORT}

    SEDS=("s|@ADVERTISED_LISTENERS@|advertised.listeners=PLAINTEXT://:9092,${KAFKA_ADVERTISED_LISTENERS}|")

    printf '\n%s\n' "${SEDS[@]}" | sed -f - /etc/kafka-config-ro/server.properties > /etc/kafka-config-rw/server.properties.snippet

    cat /etc/kafka-config-rw/server.properties.snippet >> /opt/kafka/config/server.properties

  server.properties: |-
    # Hostname and port the broker will advertise to producers and consumers. If not set, 
    # it uses the value for "listeners" if configured.  Otherwise, it will use the value
    # returned from java.net.InetAddress.getCanonicalHostName().
    @ADVERTISED_LISTENERS@ 

