---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: kafka2
spec:
  template:
    metadata:
      labels:
        app: kafka
        id: "2"
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_PORT
          value: "30866"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: 192.168.99.106
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo1:2181
        - name: KAFKA_BROKER_ID
          value: "2"
        - name: KAFKA_CREATE_TOPICS
          value: test:1:1

