---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  serviceName: kafka-service
  replicas: 3 
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      initContainers:
        - name: init-config
          image: solsson/kafka-initutils@sha256:f6d9850c6c3ad5ecc35e717308fddb47daffbde18eb93e98e031128fe8b899ef
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          command: ['/bin/bash', '/etc/kafka-config/generate-config.sh']
          volumeMounts:
          - name: kafka-config-volume
            mountPath: /etc/kafka-config
      #affinity:
      #  podAntiAffinity:
      #    requiredDuringSchedulingIgnoredDuringExecution:
      #      - labelSelector:
      #          matchExpressions:
      #            - key: app
      #              operator: In
      #              values: ["kafka"]
      #        topologyKey: "kubernetes.io/hostname"
      #  podAffinity:
      #    preferredDuringSchedulingIgnoredDuringExecution:
      #      - weight: 1
      #        podAffinityTerm:
      #          labelSelector:
      #             matchExpressions:
      #               - key: app
      #                 operator: In
      #                 values: ["zoo0"]
      #          topologyKey: "kubernetes.io/hostname"
      containers:
        - name: kafka
          image: wurstmeister/kafka
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://:9092
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zoo0:2181
            - name: KAFKA_BROKER_ID
              value: "-1"
          volumeMounts:
            - name: kafka-config-volume
              mountPath: /etc/kafka-config
            - name: data
              mountPath: /var/lib/kafka
          resources:
            requests:
              memory: "1Gi"
      volumes:
        - name: kafka-config-volume
          configMap:
            name: kafka-config
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
