apiVersion: v1
kind: Service
metadata:
  name: external-service-1
  namespace: kafka
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    statefulset.kubernetes.io/pod-name: kafka-1
  ports:
  - protocol: TCP
    port: 32401 
    targetPort: 9092
