apiVersion: v1
kind: Service
metadata:
  name: external-service-0
  namespace: kafka
spec:
  type: NodePort
  selector:
    statefulset.kubernetes.io/pod-name: kafka-0
  ports:
  - protocol: TCP
    port: 32400
    nodePort: 32400
    targetPort: 9094
