apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../namespace
- ../kafka
- ../zookeeper
- kafka/kafka3-external-service.yaml
- kafka/kafka4-external-service.yaml
patches:
- kafka/kafka-statefulset.yaml
- kafka/kafka-pdb.yaml
